#!/bin/bash  
javac StudentController.java
javac FacultyController.java
javac AdminController.java
javac Admin.java
javac AdminHome.java
javac App.java
javac Booking.java
javac ClashCheckApp.java
javac Course.java
javac CsvReader.java
javac csvtoCourse.java
javac datedayconversion.java
javac Faculty.java
javac FacultyHome.java
javac Login.java
javac loginController.java
javac RequestedRoom.java
javac Room.java
javac Search.java
javac Student.java
javac StudentHome.java
javac Time.java
javac User.java
java Login